### ISSUE TITLE
The calculating of CBR

### ISSUE THREAD

**Issue by xuanloc088** [KeYang8/WITT#10]
First, I would like to thank you for providing the code so that we can understand your paper more clearly. However, I have one concern about this code is that the way you calculate the CBR. In the code,  CBR= feature.numel() / 2 / input_image.numel().  I understand why you take the feature / input image, but I don't understand why you take the feature.numel()/2. If you don't mind, can you tell me the reason why, that would be great. Once again, thank you for the great work.

**Comment by KeYang8** [comment]
Because our paper uses complex signals for transmission.

**Comment by xuanloc088** [comment]
Thank you for your answer, I have looked into the channel code and realize that you divide the first half of the feature to real components and the other half into imaginary components. I understand it now. Thank you very much
