### ISSUE TITLE
 increase the number of transformer blocks in the CIFAR10 dataset

### ISSUE THREAD

**Issue by WenBingo** [KeYang8/WITT#11]
I want to increase the number of transformer blocks in the CIFAR10 dataset, but the process of adding keeps reporting an error。

    if args.trainset == 'CIFAR10':
        save_model_freq = 1
        image_dims = (3, 32, 32)
        train_data_dir = "./media/Dataset/CIFAR10/"
        test_data_dir = "./media/Dataset/CIFAR10/"
        batch_size = 128
        downsample = 2
        encoder_kwargs = dict(
            img_size=(image_dims[1], image_dims[2]), patch_size=2, in_chans=3,
            embed_dims=[128,192,256, 320,512], depths=[2,6,2,6,2], num_heads=[2,4,6,4,2], C=args.C,
            window_size=2, mlp_ratio=4., qkv_bias=True, qk_scale=None,
            norm_layer=nn.LayerNorm, patch_norm=True,
        )
        decoder_kwargs = dict(
            img_size=(image_dims[1], image_dims[2]),
            embed_dims=[512,320,256,192,128], depths=[2,6,2,6,2], num_heads=[2,4,6,4,2], C=args.C,
            window_size=2, mlp_ratio=4., qkv_bias=True, qk_scale=None,
            norm_layer=nn.LayerNorm, patch_norm=True,
        )

**Comment by WenBingo** [comment]
The open source code inside ended up dividing an image into 8×8 peaches, and I wanted to use 5 transformer blocks divided into 1×1 peach

**Comment by KeYang8** [comment]
You can elaborate on the problem you are experiencing.
