### ISSUE TITLE
There are some questions in the code that I would like to ask

### ISSUE THREAD

**Issue by WenBingo** [KeYang8/WITT#12]
encoder_kwargs = dict(
            img_size=(image_dims[1], image_dims[2]), patch_size=2, in_chans=3,
            embed_dims=[128, 256,512,2048], depths=[2, 4,4,4], num_heads=[2,4,4, 8], C=args.C,
            window_size=1, mlp_ratio=4., qkv_bias=True, qk_scale=None,
            norm_layer=nn.LayerNorm, patch_norm=True,
        )
        decoder_kwargs = dict(
            img_size=(image_dims[1], image_dims[2]),
            embed_dims=[2048,512,256, 128], depths=[4,4,4, 2], num_heads=[8,4, 4,2], C=args.C,
            window_size=1, mlp_ratio=4., qkv_bias=True, qk_scale=None,
            norm_layer=nn.LayerNorm, patch_norm=True,
        )

I would like to know the meaning of those amount   "depths" ,"num_heads","window_size" and " mlp_ratio"
Thank you

**Comment by KeYang8** [comment]
You can take a closer look at this paper "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows"， and maybe it will give you a clearer understanding of these amounts.
