### ISSUE TITLE
MS-SSIM指标

### ISSUE THREAD

**Issue by WenBingo** [KeYang8/WITT#13]
你好，我想请问一下项目中的MS-SSIM代码。
if args.trainset == 'CIFAR10':
    CalcuSSIM = MS_SSIM(window_size=3, data_range=1., levels=4, channel=3).cuda()      
    
else:
    CalcuSSIM = MS_SSIM(data_range=1., levels=4, channel=3).cuda()
    
  改变CIFAR10中的window_size的值（奇数），得出的SSIM指标是不同的，想问一下作者有在进行设定时的思考或者当时有没有遇到相同的问题。

**Comment by wsxtyrdd** [comment]
CIFAR10 数据集尺度太小了，所以没办法用正常的MS-SSIM指标。所以我们做了一些调整（window size 和 levels），但比较仍然是公平的。关于MS-SSIM的实现和参数配置也可以参考：https://github.com/VainF/pytorch-msssim。
