### ISSUE TITLE
复现中遇到的问题

### ISSUE THREAD

**Issue by cendy001** [KeYang8/WITT#14]
你好，我有一些问题想请教一下您：
数据集中，CLIC是一个竞赛，但是这个CLIC2021数据集是什么，可以提供吗？

谢谢您啦

**Comment by wsxtyrdd** [comment]
CLIC 竞赛在2021年使用的测试数据集， 链接： ttps://storage.googleapis.com/clic2021_public/professional_test_2021.zip
