### ISSUE TITLE
关于对比实验

### ISSUE THREAD

**Issue by fake-learn** [KeYang8/WITT#15]
作者你好，我想请问一下论文中对比的 CNN-based deep JSCC是在什么数据下训练的呢？训练的SNR是多少？

**Comment by KeYang8** [comment]
对于文中提到的对比方案，是在与本方案相同的数据集下进行训练的，每个snr的结果都是单独训练得到的

**Comment by fake-learn** [comment]
请问您能上传一下DeepJSCC相关的代码和预训练模型的权重吗
