### ISSUE TITLE
cbr是压缩率吗？为什么CBR = feature.numel() / 2 / input_image.numel()？

### ISSUE THREAD

**Issue by Tommy-shelby-github** [KeYang8/WITT#16]
您好！在network.py文件中，第60行CBR = feature.numel() / 2 / input_image.numel()意思是传输的特征的数据量/（2*原图数据量）；这里为什么有一个2倍关系？CBR是channel bandwidth ratio，代表的是什么？

**Comment by KeYang8** [comment]
假设图像是n维的，经过编码器后得到的符号为k维，则CBR=k/n。2倍是因为我们假设使用的是复数信号，所以除以2

**Comment by Tommy-shelby-github** [comment]
谢谢！

**Comment by Tommy-shelby-github** [comment]
您好！请问选取CBR=1/96时，压缩率是96倍还是48倍？

**Comment by KeYang8** [comment]
96倍
