### ISSUE TITLE
epoch

### ISSUE THREAD

**Issue by cendy001** [KeYang8/WITT#17]
你好，我看到代码中epoch的次数是100万次，实际训练需要这么多次吗？

**Comment by KeYang8** [comment]
这只是随意设置了一个上限，实际训练中几百个epoch足够了

**Comment by cendy001** [comment]
你好，我想请教一下论文中有CBR和PSNR的关系，但是在代码中没有看到相应的部分，我想请教一下CBR是如何动态调整呢？
