### ISSUE TITLE
请教一下信道部分的代码

### ISSUE THREAD

**Issue by WenBingo** [KeYang8/WITT#18]
您好，在您的channel.py中，为什么在计算sigma的时候分母要乘以2    --->>       sigma = np.sqrt((1) / (2 * 10 ** (chan_param / 10)))

        elif self.chan_type == 2 or self.chan_type == 'rayleigh':
            channel_tx1 = channel_in1
            sigma = np.sqrt((1) / (2 * 10 ** (chan_param / 10)))
            chan_output1 = self.rayleigh_noise_layer(channel_tx1,
                                                                   p,
                                                                   std=sigma,
                                                                   name="rayleigh_chan_noise")
            return chan_output1

**Comment by KeYang8** [comment]
因为我们用的是复数信道

**Comment by WenBingo** [comment]
不好意思，能否请您讲的再详细一点，我不太明白您的意思


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KeYang8/WITT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月4日(星期四) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KeYang8/WITT] 请教一下信道部分的代码 (Issue #18)





 
因为我们用的是复数信道

**Comment by KeYang8** [comment]
这里的sigma指的是复数噪声的实部或者虚部服从（0，sigma）的正态分布。我们方案中将功率进行了归一化 所以信号的功率等于1。噪声的功率Pn=Ps/（10 ** (chan_param / 10））其中Ps=1。而噪声的功率等于实部的方差和虚部的方差相加，所以实部和虚部的方差都等于Pn/2，所以sigma=np.sqrt((1) / (2 * 10 ** (chan_param / 10)))

**Comment by hias-lcj** [comment]
作者，你好。在信道部分好像没有看到关于信号恢复部分，只是将经过信道的信号进行了归一化操作？请问是只做归一化就好了嘛？还是说整体实验不用考虑信号恢复部分
