### ISSUE TITLE
请问输出图像和输入图像的尺寸有差异吗？

### ISSUE THREAD

**Issue by Tommy-shelby-github** [KeYang8/WITT#19]
您好！
我使用CLIC2024数据集，设置C=16进行实验。发现输出的图像尺寸和输入有不同，请问这是我代码调试出问题了吗？还是WITT方法会调整图像的尺寸？

**Comment by wsxtyrdd** [comment]
请保证输入图像的尺寸能够被网络下采样倍数整除，否则就要进行padding。CLIC中有一些分辨率不是16倍数的图像。
