### ISSUE TITLE
这只是随意设置了一个上限，实际训练中几百个epoch足够了

### ISSUE THREAD

**Issue by llsurreal919** [KeYang8/WITT#21]
这只是随意设置了一个上限，实际训练中几百个epoch足够了

_Originally posted by @KeYang8 in https://github.com/KeYang8/WITT/issues/17#issuecomment-1876743189_
            请问你的数据集是DVI2K中的800张HR图像吗？

**Comment by wsxtyrdd** [comment]
Yes, the dataset comprises the 800 HR images from the DIV2K dataset. Using these images, you can indeed replicate the results presented in the paper.
