### ISSUE TITLE
Cannot find model "WITT_AWGN_DIV2K_fixed_snr10_psnr_C96.model"

### ISSUE THREAD

**Issue by ghost** [KeYang8/WITT#3]
in train.py : model_path = "./WITT_model/WITT_AWGN_DIV2K_fixed_snr10_psnr_C96.model". I cannot find this file in the net disk. Could you give the lack model and explain these pre-trained models more specifically? Thank you very much.

**Comment by ghost** [comment]
Finally figure it out, but could you write the README.md more specifically? Thanks.

**Comment by KeYang8** [comment]
Sorry, I'll write the readme.md more specifically later.
