### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by xuanloc088** [KeYang8/WITT#4]
It is a great work, thank you very much for sharing the code with the community like this, I really appreciate your kindness. I have a question about the training time, how long does it take you to train 1 epoch for the CIFAR10 dataset according to the default hyperparameter, it took me around 1 hour and 15 minutes to finish one training epoch with RTX 3060 GPU. I would like to thank you in advance.

**Comment by KeYang8** [comment]
Thank you for your appreciation. Training 1 epoch for the CIFAR10 dataset took me around 15 minutes with RTX 3090 GPU.

**Comment by xuanloc088** [comment]
Thank you very much for the information, I found out some mistake in my setting, it also took me around 20 mins with RTX 3060. Thank you for the reply and I wish you have more excellent works in the future.
