### ISSUE TITLE
The pre-trained model WITT_AWGN_DIV2K_fixed_snr10_psnr_C96 is not found on Google Drive!

### ISSUE THREAD

**Issue by msalim86** [KeYang8/WITT#5]
Dear Dr. Yang,

First, I would like to congratulate you on the outstanding model.

However, I am a little bit confused about the given code, and here are some issues:
1. The pre-trained model WITT_AWGN_DIV2K_fixed_snr10_psnr_C96 is not found on Google Drive. 
2. The parser settings say that the --trainset is CIFAR10 and --testset is kodak. Should we test the model on the CIFAR10 dataset also?
3. I can't find any model in the directory WITT_model\awgn\CIFAR10 with C96.
4. Regarding the WITT_W/O. Should I just freeze the Channel ModNet module?

Thanks a lot for your patience and I wish you all the best.
Mahmoud Salim
Postdoctoral Researcher, 
School of Electrical Engineering, Korea University.

**Comment by KeYang8** [comment]
Dear Salim:
Thank you for your congratulation. I will explain your isussrs point by point:
1. The model WITT_AWGN_DIV2K_fixed_snr10_psnr_C96 you want has been uploaded, please check.
2. If the -trainset is CIFAR10 the deflaut testset is CIFAR10, and the set of -testset is invalid.
3. For the low-resolution CIFAR10 dataset, it is not need to train a model with C96.
4. The WITT_W/O model is trained without the Channel ModNet, not freezing the Channel ModNet module.
Hope the above answers can solve your confusion.

**Comment by KeYang8** [comment]
Dear Salim:
Thank you for your congratulation. I will explain your isussrs point by point:
1. The model WITT_AWGN_DIV2K_fixed_snr10_psnr_C96 you want has been uploaded, please check.
2. If the -trainset is CIFAR10 the deflaut testset is CIFAR10, and the set of -testset is invalid.
3. For the low-resolution CIFAR10 dataset, it is not need to train a model with C96.
4. The WITT_W/O model is trained without the Channel ModNet, not freezing the Channel ModNet module.

Hope the above answers can solve your confusion.

**Comment by msalim86** [comment]
Thanks a lot Dr. Yang for the useful information and I hope we can have research collaborations in the near future.

**Comment by msalim86** [comment]
Sorry, but I can't find the model "WITT_AWGN_DIV2K_fixed_snr10_psnr_C96" on Google Drive!
![image](https://user-images.githubusercontent.com/106870517/232656136-71ff8b7e-55f8-47a1-8e81-d1cf78cf4679.png)
