### ISSUE TITLE
Cannot train a good model like yours

### ISSUE THREAD

**Issue by ghost** [KeYang8/WITT#6]
During my training, I found that it can achieve great performance in some batches but also bad performance in the same SNR. I change the length of the CIFAR10 dataset (In your code its length is 10 times its original one), and in that case, when I train about 600 epochs, the best performance I can get is just PSNR=25 in SNR=1 and in some batches PSNR just around 20. So I want to ask how many epochs you trained in your original code to achieve such great performance. I trained the model in random SNR scheme.

Btw, I am also a student at BUPT, so could we have some communication about that?

**Comment by KeYang8** [comment]
I'm sorry that I don't know where you have problems. When CBR=1/3, after five training epochs, PSNR=29. Maybe you can leave your contact information for communication.

**Comment by ghost** [comment]
OK, here is my email: xingdengzb@bupt.edu.cn. You can send me an email and I can add your WeChat or something else you like.

**Comment by msalim86** [comment]
> OK, here is my email: [xingdengzb@bupt.edu.cn](mailto:xingdengzb@bupt.edu.cn). You can send me an email and I can add your WeChat or something else you like.

Hello, I hope you can solve your problem.
I was wondering, how do you determine the CBR? 
I think it is determined as a function of the channel dimensions C, right?
