### ISSUE TITLE
Problems with modulation and demodulation

### ISSUE THREAD

**Issue by eadstry** [KeYang8/WITT#8]
I noticed that the code directly divides the float type data into two parts in the modulation step before passing through the channel, and uses the second part as the imaginary part to simulate the modulation process. But this is very different from the conventional QAM or BPSK modulation method, which requires quantization into bytes of data before modulation. Is the quantization and modulation implemented in this code correct in the communication process, and is there any difference from the traditional QAM modulation method?

**Comment by KeYang8** [comment]
Our proposed model is not quantized and modulated， it is analog transmission in communication.
