### ISSUE TITLE
code of BPG+LDPC 

### ISSUE THREAD

**Issue by WenBingo** [KeYang8/WITT#9]
hello，Are you able to open source the code of BPG+LDPC

**Comment by KeYang8** [comment]
The code for BPG+LDPC will be opened in later work.

**Comment by haixiongli** [comment]
Hello, what is the specific parameter setting of LDPC inside? Such as coding rates and QAM.

**Comment by KeYang8** [comment]
For AWGN channel, we choose the configuration of coding rate and modulation as (1/3rate LDPC + 4QAM, 1/2rate LDPC + 4QAM, 2/3rate LDPC + 4QAM,1/2rate LDPC + 16QAM, 2/3rate LDPC + 16QAM, 1/2rate LDPC + 64QAM.)
For Rayleigh channel, we choose the configuration of coding rate and modulation as (1/3rate LDPC +4QAM, 1/2rate LDPC +4QAM, 2/3rate LDPC +4QAM, 1/2rate LDPC +16QAM.)

**Comment by haixiongli** [comment]
what about the block length of LDPC?

**Comment by KeYang8** [comment]
(6144,4096)

**Comment by HaixiongLi** [comment]
您好，我在尝试BPG+LDPC实验，对因您论文中Fig3.中的实验发现，如果固定BPG和LDPC的参数，随着SNR的变化，图像的PSNR并不会随着变化。请问您的实验结果中，随着SNR的调整，PSNR变化的实验，有其他的实验细节吗？

我的实验参数设置：
BPG quality=39
LDPC：6144，rate=2/3，QAM=16 
SNR: 1,4,7,40,13,16

我的结果：
PSNR = 28。06607

**Comment by KeYang8** [comment]
你可以参考一下这篇文章：“DeepJSCC-f : Deep Joint Source-Channel Coding of Images With Feedback”的Fig.16。 rate=2/3, QAM=16时应该会在10dB出现悬崖效应。
&nbsp;









杨可

北京邮电大学/研究生/人工智能学院



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "HaixiongLi"; 
Date: 2023年5月26日(星期五) 中午11:05
To: "KeYang8/WITT"; 
Cc: "杨可"; "Comment"; 
Subject: Re: [KeYang8/WITT] code of BPG+LDPC  (Issue #9)

&nbsp;


 
您好，我在尝试BPG+LDPC实验，对因您论文中Fig3.中的实验发现，如果固定BPG和LDPC的参数，随着SNR的变化，图像的PSNR并不会随着变化。请问您的实验结果中，随着SNR的调整，PSNR变化的实验，有其他的实验细节吗？
 
我的实验参数设置：
 BPG quality=39
 LDPC：6144，rate=2/3，QAM=16
 SNR: 1,4,7,40,13,16
 
我的结果：
 PSNR = 28。06607

**Comment by haixiongli** [comment]
您好，我在复现时总是出现和你的指标不一致的问题，能不能加一下您的微信，我的微信是18681890201，非常感谢

**Comment by wsxtyrdd** [comment]
> hello，Are you able to open source the code of BPG+LDPC
Please refer to this repo https://github.com/kmsiapps/Semantic-Communications-with-a-Vision-Transformer/blob/main/bpg-ldpc.ipynb
